"""auto-migracion

Revision ID: 030109b8bc6d
Revises: 26b5b31f0a7e
Create Date: 2026-04-30 18:42:48.741585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '030109b8bc6d'
down_revision: Union[str, None] = '26b5b31f0a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proyectos', 'prueba1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos', sa.Column('prueba1', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
