"""auto-migracion

Revision ID: 24d0192e3812
Revises: 2fac21969a43
Create Date: 2026-04-30 18:05:55.961479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24d0192e3812'
down_revision: Union[str, None] = '2fac21969a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos', sa.Column('prueba', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proyectos', 'prueba')
    # ### end Alembic commands ###
