"""auto-deploy

Revision ID: 26b5b31f0a7e
Revises: 72ccd3ca30b3
Create Date: 2026-04-30 18:38:23.968056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b5b31f0a7e'
down_revision: Union[str, None] = '72ccd3ca30b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos', sa.Column('prueba1', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proyectos', 'prueba1')
    # ### end Alembic commands ###
