"""auto-migracion

Revision ID: 2fac21969a43
Revises: 7229ec6ca312
Create Date: 2026-04-30 15:29:53.518666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fac21969a43'
down_revision: Union[str, None] = '7229ec6ca312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('presupuesto', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyectos_id'), 'proyectos', ['id'], unique=False)
    op.create_index(op.f('ix_proyectos_nombre'), 'proyectos', ['nombre'], unique=False)
    op.add_column('empleados', sa.Column('fecha_ingreso', sa.String(), nullable=True))
    op.add_column('empleados', sa.Column('salario', sa.Integer(), nullable=True))
    op.add_column('empleados', sa.Column('departamento', sa.String(), nullable=True))
    op.add_column('empresas', sa.Column('telefono', sa.String(), nullable=True))
    op.add_column('empresas', sa.Column('direccion', sa.String(), nullable=True))
    op.add_column('empresas', sa.Column('cuit', sa.String(), nullable=True))
    op.add_column('empresas', sa.Column('rubro', sa.String(), nullable=True))
    op.add_column('empresas', sa.Column('website', sa.String(), nullable=True))
    op.drop_column('empresas', 'telefonito')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('telefonito', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('empresas', 'website')
    op.drop_column('empresas', 'rubro')
    op.drop_column('empresas', 'cuit')
    op.drop_column('empresas', 'direccion')
    op.drop_column('empresas', 'telefono')
    op.drop_column('empleados', 'departamento')
    op.drop_column('empleados', 'salario')
    op.drop_column('empleados', 'fecha_ingreso')
    op.drop_index(op.f('ix_proyectos_nombre'), table_name='proyectos')
    op.drop_index(op.f('ix_proyectos_id'), table_name='proyectos')
    op.drop_table('proyectos')
    # ### end Alembic commands ###
