"""auto-migracion

Revision ID: 7229ec6ca312
Revises: 9828e4cd61fd
Create Date: 2026-04-30 15:16:49.800693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7229ec6ca312'
down_revision: Union[str, None] = '9828e4cd61fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('telefonito', sa.String(), nullable=True))
    op.drop_column('empresas', 'celularcito')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('celularcito', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('empresas', 'telefonito')
    # ### end Alembic commands ###
