"""auto-migracion

Revision ID: 72ccd3ca30b3
Revises: ae1d156d5b91
Create Date: 2026-04-30 18:34:52.771553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ccd3ca30b3'
down_revision: Union[str, None] = 'ae1d156d5b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proyectos', 'prueba5')
    op.drop_column('proyectos', 'prueba7')
    op.drop_column('proyectos', 'prueba2')
    op.drop_column('proyectos', 'prueba6')
    op.drop_column('proyectos', 'prueba3')
    op.drop_column('proyectos', 'prueba')
    op.drop_column('proyectos', 'prueba4')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos', sa.Column('prueba4', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('proyectos', sa.Column('prueba', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('proyectos', sa.Column('prueba3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('proyectos', sa.Column('prueba6', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('proyectos', sa.Column('prueba2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('proyectos', sa.Column('prueba7', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('proyectos', sa.Column('prueba5', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
