"""auto-deploy

Revision ID: 82100ad49491
Revises: 99dfb1b34568
Create Date: 2026-04-30 18:26:10.655062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82100ad49491'
down_revision: Union[str, None] = '99dfb1b34568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos', sa.Column('prueba4', sa.String(), nullable=True))
    op.add_column('proyectos', sa.Column('prueba5', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proyectos', 'prueba5')
    op.drop_column('proyectos', 'prueba4')
    # ### end Alembic commands ###
