"""Agregar rol a Empleado

Revision ID: 8aaeb18e5418
Revises: a2f644e0bb92
Create Date: 2026-04-29 14:25:09.510317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aaeb18e5418'
down_revision: Union[str, None] = 'a2f644e0bb92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('rol', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empleados', 'rol')
    # ### end Alembic commands ###
