"""auto-migracion

Revision ID: 9828e4cd61fd
Revises: e04a4b329e05
Create Date: 2026-04-30 15:14:43.454787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9828e4cd61fd'
down_revision: Union[str, None] = 'e04a4b329e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('email', sa.String(), server_default='sin_correo@empresa.com', nullable=False))
    op.add_column('empresas', sa.Column('celularcito', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'celularcito')
    op.drop_column('empleados', 'email')
    # ### end Alembic commands ###
