"""auto-deploy

Revision ID: 99dfb1b34568
Revises: ee16afecce44
Create Date: 2026-04-30 18:24:48.518318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99dfb1b34568'
down_revision: Union[str, None] = 'ee16afecce44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos', sa.Column('prueba3', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proyectos', 'prueba3')
    # ### end Alembic commands ###
