"""Renombrar rol a cargo

Revision ID: a72385ef404d
Revises: 8aaeb18e5418
Create Date: 2026-04-29 15:22:14.457371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a72385ef404d'
down_revision: Union[str, None] = '8aaeb18e5418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empleados', 'rol', new_column_name='cargo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empleados', 'cargo', new_column_name='rol')
    # ### end Alembic commands ###
