"""auto-migracion

Revision ID: ae1d156d5b91
Revises: 82100ad49491
Create Date: 2026-04-30 18:27:16.900600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1d156d5b91'
down_revision: Union[str, None] = '82100ad49491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos', sa.Column('prueba6', sa.String(), nullable=True))
    op.add_column('proyectos', sa.Column('prueba7', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proyectos', 'prueba7')
    op.drop_column('proyectos', 'prueba6')
    # ### end Alembic commands ###
