"""add_email_to_empleado

Revision ID: cd295cf521ea
Revises: e04a4b329e05
Create Date: 2026-04-29 18:22:23.348398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd295cf521ea'
down_revision: Union[str, None] = 'e04a4b329e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empleados', 'email')
    # ### end Alembic commands ###
