"""rename_nombre_to_name

Revision ID: e04a4b329e05
Revises: a72385ef404d
Create Date: 2026-04-29 15:41:24.961955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04a4b329e05'
down_revision: Union[str, None] = 'a72385ef404d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('name', sa.String(), nullable=True))
    op.drop_index('ix_empleados_nombre', table_name='empleados')
    op.create_index(op.f('ix_empleados_name'), 'empleados', ['name'], unique=False)
    op.drop_column('empleados', 'nombre')
    op.add_column('empresas', sa.Column('name', sa.String(), nullable=True))
    op.drop_index('ix_empresas_nombre', table_name='empresas')
    op.create_index(op.f('ix_empresas_name'), 'empresas', ['name'], unique=False)
    op.drop_column('empresas', 'nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_empresas_name'), table_name='empresas')
    op.create_index('ix_empresas_nombre', 'empresas', ['nombre'], unique=False)
    op.drop_column('empresas', 'name')
    op.add_column('empleados', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_empleados_name'), table_name='empleados')
    op.create_index('ix_empleados_nombre', 'empleados', ['nombre'], unique=False)
    op.drop_column('empleados', 'name')
    # ### end Alembic commands ###
