"""auto-deploy

Revision ID: ee16afecce44
Revises: 24d0192e3812
Create Date: 2026-04-30 18:18:31.007727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee16afecce44'
down_revision: Union[str, None] = '24d0192e3812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos', sa.Column('prueba2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proyectos', 'prueba2')
    # ### end Alembic commands ###
